(()=>{
'use strict';
const form=document.getElementById('contact-form');if(!form)return;
const q=id=>document.getElementById(id),cfg=window.HLUSTADU_CONTACT||{};
let mode='text',recorder,stream,timer,startTime,blob,url,seconds=0,sending=false,requestingMic=false,widget;
const status=text=>{q('form-status').textContent=text;};
const tracksOff=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;};
function clearRecording(){clearInterval(timer);if(recorder?.state==='recording')recorder.stop();tracksOff();blob=null;seconds=0;if(url)URL.revokeObjectURL(url);url=null;q('record-audio').removeAttribute('src');q('record-idle').hidden=false;q('record-active').hidden=true;q('record-ready').hidden=true;}
function setMode(next){if(sending||requestingMic||recorder?.state==='recording')return;mode=next;q('textpanel').classList.toggle('hidden',next!=='text');q('voicepanel').classList.toggle('hidden',next!=='voice');q('message').required=next==='text';form.querySelectorAll('[data-mode]').forEach(b=>{const selected=b.dataset.mode===next;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected));});status('');}
form.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
async function record(){if(sending)return;clearRecording();status('');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status('Þessi vafri styður ekki upptöku. Skrifaðu okkur skilaboð í staðinn.');return;}
requestingMic=true;q('record-start').disabled=true;form.querySelectorAll('[data-mode],#contact-send').forEach(b=>b.disabled=true);
try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:64000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{clearInterval(timer);tracksOff();blob=new Blob(chunks,{type:recorder.mimeType||chunks[0]?.type||'audio/webm'});if(!blob.size||blob.size>2500000){clearRecording();status('Upptakan tókst ekki eða skráin er of stór. Reyndu styttri upptöku eða skrifaðu skilaboð.');return;}url=URL.createObjectURL(blob);q('record-audio').src=url;q('record-active').hidden=true;q('record-ready').hidden=false;};recorder.onerror=()=>{clearRecording();status('Upptakan mistókst. Reyndu aftur eða skrifaðu skilaboð.');};q('record-idle').hidden=true;q('record-active').hidden=false;recorder.start(1000);startTime=Date.now();q('record-time').textContent='0:00 / 1:30';timer=setInterval(()=>{seconds=Math.min(90,Math.floor((Date.now()-startTime)/1000));q('record-time').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')+' / 1:30';if(seconds>=90)recorder.stop();},250);
}catch(e){tracksOff();status(e.name==='NotAllowedError'?'Aðgangur að hljóðnemanum var ekki veittur. Þú getur skrifað skilaboð eða leyft aðgang í stillingum vafrans.':'Ekki náðist samband við hljóðnemann. Prófaðu aftur eða skrifaðu skilaboð.');}finally{requestingMic=false;q('record-start').disabled=false;form.querySelectorAll('[data-mode],#contact-send').forEach(b=>b.disabled=false);}}
q('record-start').addEventListener('click',record);q('record-stop').addEventListener('click',()=>{if(recorder?.state==='recording')recorder.stop();});q('record-again').addEventListener('click',record);q('record-delete').addEventListener('click',()=>{clearRecording();status('Upptökunni hefur verið eytt. Engin upptaka fylgir skilaboðunum.');});
form.addEventListener('submit',async e=>{e.preventDefault();if(sending||requestingMic)return;if(recorder?.state==='recording'){status('Stöðvaðu upptökuna áður en þú sendir.');return;}if(!form.reportValidity())return;if(mode==='text'&&!q('message').value.trim()){status('Skrifaðu skilaboð áður en þú sendir.');q('message').focus();return;}if(mode==='voice'&&!blob){status('Taktu upp skilaboð áður en þú sendir, eða veldu „Skrifa skilaboð“.');return;}if(!cfg.endpoint){status('Sendingar eru ekki tilbúnar enn. Sendu okkur tölvupóst á hlustadu@hlustadu.is.');return;}const token=window.turnstile?.getResponse(widget);if(!token){status('Bíddu eftir öryggisathuguninni og reyndu aftur.');return;}const data=new FormData(form);data.set('mode',mode);data.set('cf-turnstile-response',token);if(mode==='voice'){data.set('message','');const ext=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';data.set('audio',blob,'skilabod.'+ext);data.set('duration',String(Math.max(1,seconds)));}sending=true;form.querySelectorAll('button,input,textarea').forEach(b=>b.disabled=true);status('Sendi skilaboðin…');try{const response=await fetch(cfg.endpoint,{method:'POST',body:data});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Sending tókst ekki.');form.reset();clearRecording();sending=false;setMode('text');status('Takk fyrir! Skilaboðin hafa verið send. Við svörum á netfangið sem þú gafst upp.');}catch(e){status('Sending tókst ekki. Skilaboðin þín eru enn hér. Reyndu aftur eða sendu tölvupóst á hlustadu@hlustadu.is.');}finally{sending=false;form.querySelectorAll('button,input,textarea').forEach(b=>b.disabled=false);window.turnstile?.reset(widget);}});
window.hlustaduTurnstileReady=()=>{widget=window.turnstile.render('#spam-check',{sitekey:cfg.sitekey,action:'contact',appearance:'interaction-only',size:window.matchMedia('(max-width:380px)').matches?'compact':'normal',theme:'light','error-callback':()=>status('Öryggisathugunin náðist ekki. Reyndu aftur eða sendu okkur tölvupóst.')});};
if(cfg.sitekey){const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?onload=hlustaduTurnstileReady&render=explicit';script.async=true;document.head.appendChild(script);}setMode('text');window.addEventListener('pagehide',tracksOff);document.addEventListener('visibilitychange',()=>{if(document.hidden&&recorder?.state==='recording'){recorder.stop();status('Upptakan var stöðvuð þegar þú fórst af síðunni. Þú getur hlustað eða tekið aftur.');}});
})();
